import type { BookingFormData } from '@/components/booking-system-types';

/** Default wizard state — public booking flow (`BookingSystem`). */
export const WIZARD_DEFAULT_FORM: BookingFormData = {
  service: 'standard',
  bedrooms: 2,
  bathrooms: 1,
  extraRooms: 0,
  propertyType: 'apartment',
  officeSize: '',
  extras: [],
  extrasQuantities: {},
  cleanerId: '',
  teamId: '',
  workingArea: '',
  date: '',
  time: '',
  name: '',
  email: '',
  phone: '',
  address: '',
  instructions: '',
  paymentMethod: 'online',
  tipAmount: 0,
  promoCode: '',
  discountAmount: 0,
  officeBoardrooms: 1,
  officePrivateOffices: 1,
  officeOpenAreas: 1,
  officeBathrooms: 1,
  officeKitchens: 1,
  officeHasReception: false,
  carpetRooms: 1,
  carpetRugs: 0,
  carpetExtraCleaner: false,
  numberOfCleaners: 1,
  teamSizeUserOverride: false,
  pricingMode: 'basic',
  basicPlannedHours: 3,
};
